-- MySQL Script generated by MySQL Workbench
-- Mon Mar  9 11:53:12 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shopMall
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shopMall
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shopMall` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `shopMall` ;

-- -----------------------------------------------------
-- Table `shopMall`.`members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopMall`.`members` (
  `member_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `birth_date` DATE NULL DEFAULT NULL,
  `grade` ENUM('BRONZE', 'SILVER', 'GOLD', 'VIP') NULL DEFAULT 'BRONZE',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`member_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopMall`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopMall`.`categories` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(50) NOT NULL,
  `parent_category_id` INT NULL DEFAULT NULL,
  `depth` TINYINT NULL DEFAULT '1',
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopMall`.`coupons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopMall`.`coupons` (
  `coupon_id` INT NOT NULL AUTO_INCREMENT,
  `copon_name` VARCHAR(100) NOT NULL,
  `discount_type` ENUM('PERCENT', 'FIXED') NOT NULL,
  `discount_value` DECIMAL(10,2) NOT NULL,
  `min_order_amount` DECIMAL(10,2) NULL DEFAULT '0.00',
  `valid_from` DATE NOT NULL,
  `valid_until` DATE NOT NULL,
  PRIMARY KEY (`coupon_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopMall`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopMall`.`addresses` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `member_id` INT NOT NULL,
  `address_name` VARCHAR(50) NOT NULL,
  `recipient` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `zipcode` VARCHAR(10) NOT NULL,
  `address` VARCHAR(200) NOT NULL,
  `detail_address` VARCHAR(100) NULL DEFAULT NULL,
  `is_default` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopMall`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopMall`.`products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `product_name` VARCHAR(200) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `stock` INT NULL DEFAULT '0',
  `description` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopMall`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopMall`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `member_id` INT NOT NULL,
  `address_id` INT NOT NULL,
  `order_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `status` ENUM('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED') NOT NULL DEFAULT 'PENDING',
  `total_amount` DECIMAL(10,2) NULL,
  PRIMARY KEY (`order_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopMall`.`order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopMall`.`order_items` (
  `order_item_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL DEFAULT '1',
  `unit_price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`order_item_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopMall`.`cart_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopMall`.`cart_items` (
  `cart_item_id` INT NOT NULL AUTO_INCREMENT,
  `member_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL DEFAULT '1',
  `added_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`cart_item_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopMall`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopMall`.`reviews` (
  `review_id` INT NOT NULL AUTO_INCREMENT,
  `member_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `rating` TINYINT NOT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`review_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopMall`.`coupon_issues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopMall`.`coupon_issues` (
  `coupon_issue_id` INT NOT NULL AUTO_INCREMENT,
  `coupon_id` INT NOT NULL,
  `member_id` INT NOT NULL,
  `order_id` INT NULL DEFAULT NULL,
  `issued_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `used_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`coupon_issue_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
